
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILED = 'GET_USER_FAILED'

export const USER_SET = 'USER_SET'

export const USER_PATCH_REQUEST = 'USER_PATCH_REQUEST'
export const USER_PATCH_SUCCESS = 'USER_PATCH_SUCCESS'
export const USER_PATCH_FAILED = 'USER_PATCH_FAILED'

export const USER_UPDATE = 'USER_UPDATE'

export const AUTH_CHECKED = 'AUTH_CHECKED'


export const ADD_CONSTRUCTOR_ITEM = 'ADD_CONSTRUCTOR_ITEM';
export const REMOVE_CONSTRUCTOR_ITEM = 'REMOVE_CONSTRUCTOR_ITEM';
export const MOVE_CONSTRUCTOR_ITEM = 'MOVE_CONSTRUCTOR_ITEM';
export const RESET_CONSTRUCTOR_ITEMS = 'RESET_CONSTRUCTOR_ITEMS';


export const INGREDIENT_DETAIL_SET = 'INGREDIENT_DETAIL_SET_DATA';
export const SET_BROWSED_CATEGORY = 'SET_BROWSED_CATEGORY';


export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';


export const MAKE_ORDER_REQUEST = 'MAKE_ORDER_REQUEST';
export const MAKE_ORDER_SUCCESS = 'MAKE_ORDER_SUCCESS';
export const MAKE_ORDER_FAILED = 'MAKE_ORDER_FAILED';


export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';


export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';


export const ORDERS_FEED_CONNECTION_START = 'ORDERS_FEED_CONNECTION_START';
export const ORDERS_FEED_CONNECTING = 'ORDERS_FEED_CONNECTING';
export const ORDERS_FEED_CONNECTION_STOP = 'ORDERS_FEED_CONNECTION_STOP';

export const ORDERS_FEED_CONNECTION_SUCCESS = 'ORDERS_FEED_CONNECTION_SUCCESS';
export const ORDERS_FEED_CONNECTION_CLOSED = 'ORDERS_FEED_CONNECTION_CLOSED';
export const ORDERS_FEED_CONNECTION_ERROR = 'ORDERS_FEED_CONNECTION_ERROR';
export const ORDERS_FEED_GET_MESSAGE = 'ORDERS_FEED_GET_MESSAGE';
export const ORDERS_FEED_SEND_MESSAGE = 'ORDERS_FEED_SEND_MESSAGE';


export const ORDERS_HISTORY_CONNECTION_START = 'ORDERS_HISTORY_CONNECTION_START';
export const ORDERS_HISTORY_CONNECTING = 'ORDERS_HISTORY_CONNECTING';
export const ORDERS_HISTORY_CONNECTION_STOP = 'ORDERS_HISTORY_CONNECTION_STOP';

export const ORDERS_HISTORY_CONNECTION_SUCCESS = 'ORDERS_HISTORY_CONNECTION_SUCCESS';
export const ORDERS_HISTORY_CONNECTION_CLOSED = 'ORDERS_HISTORY_CONNECTION_CLOSED';
export const ORDERS_HISTORY_CONNECTION_ERROR = 'ORDERS_HISTORY_CONNECTION_ERROR';
export const ORDERS_HISTORY_GET_MESSAGE = 'ORDERS_HISTORY_GET_MESSAGE';
export const ORDERS_HISTORY_SEND_MESSAGE = 'ORDERS_HISTORY_SEND_MESSAGE';