export const SHOW_INGREDIENT_DETAIL_MODAL = 'SHOW_INGREDIENT_DETAIL_MODAL';
export const HIDE_INGREDIENT_DETAIL_MODAL = 'HIDE_INGREDIENT_DETAIL_MODAL';

export const SET_BROWSED_CATEGORY = 'SET_BROWSED_CATEGORY';